(function() {var implementors = {};
implementors["smithay"] = [{text:"impl&lt;T:&nbsp;'static, A:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> + 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay/backend/graphics/egl/context/struct.EGLContext.html\" title=\"struct smithay::backend::graphics::egl::context::EGLContext\">EGLContext</a>&lt;<a class=\"struct\" href=\"smithay/backend/graphics/egl/native/struct.Gbm.html\" title=\"struct smithay::backend::graphics::egl::native::Gbm\">Gbm</a>&lt;T&gt;, GbmDevice&lt;A&gt;&gt;",synthetic:false,types:["smithay::backend::graphics::egl::context::EGLContext"]},{text:"impl&lt;A:&nbsp;Device + 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay/backend/drm/struct.DrmBackend.html\" title=\"struct smithay::backend::drm::DrmBackend\">DrmBackend</a>&lt;A&gt;",synthetic:false,types:["smithay::backend::drm::backend::DrmBackend"]},{text:"impl&lt;A:&nbsp;ControlDevice + 'static&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay/backend/drm/struct.DrmDevice.html\" title=\"struct smithay::backend::drm::DrmDevice\">DrmDevice</a>&lt;A&gt;",synthetic:false,types:["smithay::backend::drm::DrmDevice"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/sys/unix/ext/io/trait.AsRawFd.html\" title=\"trait std::sys::unix::ext::io::AsRawFd\">AsRawFd</a> for <a class=\"struct\" href=\"smithay/backend/udev/struct.SessionFdDrmDevice.html\" title=\"struct smithay::backend::udev::SessionFdDrmDevice\">SessionFdDrmDevice</a>",synthetic:false,types:["smithay::backend::udev::SessionFdDrmDevice"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
