(function() {var implementors = {};
implementors["smithay"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"smithay/backend/graphics/egl/context/struct.PixelFormatRequirements.html\" title=\"struct smithay::backend::graphics::egl::context::PixelFormatRequirements\">PixelFormatRequirements</a>",synthetic:false,types:["smithay::backend::graphics::egl::context::PixelFormatRequirements"]},{text:"impl&lt;U:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"smithay/wayland/compositor/struct.SurfaceAttributes.html\" title=\"struct smithay::wayland::compositor::SurfaceAttributes\">SurfaceAttributes</a>&lt;U&gt;",synthetic:false,types:["smithay::wayland::compositor::SurfaceAttributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"smithay/wayland/compositor/struct.SubsurfaceRole.html\" title=\"struct smithay::wayland::compositor::SubsurfaceRole\">SubsurfaceRole</a>",synthetic:false,types:["smithay::wayland::compositor::SubsurfaceRole"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"smithay/wayland/compositor/struct.RegionAttributes.html\" title=\"struct smithay::wayland::compositor::RegionAttributes\">RegionAttributes</a>",synthetic:false,types:["smithay::wayland::compositor::RegionAttributes"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"smithay/wayland/shell/xdg/enum.XdgSurfacePendingState.html\" title=\"enum smithay::wayland::shell::xdg::XdgSurfacePendingState\">XdgSurfacePendingState</a>",synthetic:false,types:["smithay::wayland::shell::xdg::XdgSurfacePendingState"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
